name: professional_locator
description: A new Flutter project.

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.6

  # Add Firebase dependencies (optional, based on your project needs)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # If you have assets (like images), you can add them here
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # For custom fonts, define them here
  fonts:
    - family: Roboto
      fonts:
        - asset: assets\fonts\Roboto\Roboto-BoldItalic.ttf
        - asset: assets\fonts\Roboto\Roboto-Bold.ttf
          weight: 700
